@isTest
public class TestForce {
    static testMethod void demoTest() {
    /*
        //List<Orders__x> orde = [ SELECT Id,ExternalId FROM Orders__x LIMIT 1];
        
        Test.StartTest();
        Orders__x  ord = new Orders__x();
        ord.ShipCountry__c = 'test';
        ord.ExternalId = '10248';
        ord.ExternalId = System.Label.Exter_Obj_Val;
        //system.debug('::::::ORDE::'+orde );
       // insert ord;
        ApexPages.StandardController std = new ApexPages.StandardController(ord );
        externalObjectDemo controllerInstance = new externalObjectDemo (std);
        System.Assert( controllerInstance.ordDetails12 != NULL );
        System.Assert(controllerInstance.ordDetails12.size() >= 1 );
        system.debug('::::::::'+controllerInstance.ordDetails12.size());
        Test.StopTest();
       // insert ord;*/
    }
   
    }